/**
 * others
 * @author sarkiroka on 2017.02.21.
 */
export default {
	'no-constant-condition': ['error'],
	'no-control-regex': ['error'],
	'no-delete-var': ['error'],
	'no-div-regex': ['error'],
	'no-duplicate-case': ['error'],
	'no-empty-character-class': ['error'],
	'no-ex-assign': ['error'],
	'no-extend-native': ['error'],
	'no-extra-bind': ['error'],
	'no-extra-boolean-cast': ['error'],
	'no-extra-parens': ['error'],
	'no-fallthrough': ['error'],
	'no-floating-decimal': ['error'],
	'no-func-assign': ['error'],
	'no-implied-eval': ['error'],
	'no-inner-declarations': ['error'],
	'no-invalid-regexp': ['error'],
	'no-iterator': ['error'],
	'no-label-var': ['error'],
	'no-labels': ['error'],
	'no-multi-str': ['error'],
	'no-multiple-empty-lines': ['error'],
	'no-native-reassign': ['error'],
	'no-negated-in-lhs': ['error'],
	'no-nested-ternary': ['error'],
	'no-new': ['error'],
	'no-new-func': ['error'],
	'no-new-object': ['error'],
	'no-new-require': ['error'],
	'no-new-wrappers': ['error'],
	'no-obj-calls': ['error'],
	'no-octal': ['error'],
	'no-octal-escape': ['error'],
	'no-undef': ['error'],
	'no-path-concat': ['error'],
	'no-proto': ['error'],
	'no-redeclare': ['error'],
	'no-return-assign': ['error'],
	'no-self-compare': ['error'],
	'no-sequences': ['error'],
	'no-shadow': ['error'],
	'no-shadow-restricted-names': ['error'],
	'no-sparse-arrays': ['error'],
	'no-throw-literal': ['error'],
	'no-unexpected-multiline': ['error'],
	'no-unneeded-ternary': ['error'],
	'no-unused-vars': ['error'],
	'no-use-before-define': ['error'],
	'no-useless-call': ['error'],
	'no-void': ['error'],
	'no-with': ['error'],
	'operator-linebreak': ['error', 'after'],
	'operator-assignment': ['error'],
	'quote-props': ['error', 'consistent-as-needed'],
	'use-isnan': ['error'],
	'valid-typeof': ['error'],
	'wrap-iife': ['error']
};
