/**
 * others
 * @author sarkiroka on 2017.02.21.
 */
module.exports = {
	'no-constant-condition':       [2],
	'no-control-regex':            [2],
	'no-delete-var':               [2],
	'no-div-regex':                [2],
	'no-duplicate-case':           [2],
	'no-empty-character-class':    [2],
	'no-ex-assign':                [2],
	'no-extend-native':            [2],
	'no-extra-bind':               [2],
	'no-extra-boolean-cast':       [2],
	'no-extra-parens':             [2],
	'no-fallthrough':              [2],
	'no-floating-decimal':         [2],
	'no-func-assign':              [2],
	'no-implied-eval':             [2],
	'no-inner-declarations':       [2],
	'no-invalid-regexp':           [2],
	'no-iterator':                 [2],
	'no-label-var':                [2],
	'no-labels':                   [2],
	'no-multi-str':                [2],
	'no-multiple-empty-lines':     [2],
	'no-native-reassign':          [2],
	'no-negated-in-lhs':           [2],
	'no-nested-ternary':           [2],
	'no-new':                      [2],
	'no-new-func':                 [2],
	'no-new-object':               [2],
	'no-new-require':              [2],
	'no-new-wrappers':             [2],
	'no-obj-calls':                [2],
	'no-octal':                    [2],
	'no-octal-escape':             [2],
	'no-undef':                    [2],
	'no-path-concat':              [2],
	'no-proto':                    [2],
	'no-redeclare':                [2],
	'no-return-assign':            [2],
	'no-self-compare':             [2],
	'no-sequences':                [2],
	'no-shadow':                   [2],
	'no-shadow-restricted-names':  [2],
	'no-sparse-arrays':            [2],
	'no-throw-literal':            [2],
	'no-unexpected-multiline':     [2],
	'no-unneeded-ternary':         [2],
	'no-unused-vars':              [2],
	'no-use-before-define':        [2],
	'no-useless-call':             [2],
	'no-void':                     [2],
	'no-with':                     [2],
	'operator-linebreak':          [2, 'after'],
	'operator-assignment':         [2],
	'quote-props':                 [2, 'consistent-as-needed'],
	'use-isnan':                   [2],
	'valid-typeof':                [2],
	'wrap-iife':                   [2]
};
